In [1]:
import numpy as np
from tkinter import *
from update_state import *
from distance import Distance
import tkinter 

from visualize import target_grid_to_image

In [2]:
%reload_ext autoreload
%autoreload 2

* Empty(E) : White
* Pedestrian(P) : Red
* Target(T) : Yellow
* Obstacle(O) : Violet

In [3]:
class Cell():
    EMPTY_COLOR_BG = "white"
    EMPTY_COLOR_BORDER = "black"
    
    COLOR_DICT = {'empty':'white','pedestrian':'red', 'target':'yellow','obstacle':'violet'}
    CELL_ENUM = {'empty':0,'pedestrian':1, 'target':2, 'obstacle':3} 
    CELL_STATE = ['empty','pedestrian', 'target', 'obstacle']
    
    def __init__(self, master, x, y, size, init_cell_state=None):
        """ Constructor of the object called by Cell(...) """
        
        self.master = master
        self.x = x
        self.y = y
        self.size = size
        
        if init_cell_state==None:
            self.enum_val = 0
        
        else:
            self.enum_val = Cell.CELL_ENUM[init_cell_state]
        
        self.state = Cell.CELL_STATE[self.enum_val]
        
    def _switch(self):
        """ Toggle Cell State """
        
        self.enum_val += 1

    def draw(self, state=None):
        """ order to the cell to draw its representation on the canvas """
        # 
        if self.master != None :
            outline = Cell.EMPTY_COLOR_BORDER
            if state==None:
                
                self.state = Cell.CELL_STATE[self.enum_val % len(Cell.CELL_STATE)]
            else:
                self.state = state
            fill = Cell.COLOR_DICT[self.state]
            outline = Cell.EMPTY_COLOR_BORDER

            xmin = self.x * self.size
            xmax = xmin + self.size
            ymin = self.y * self.size
            ymax = ymin + self.size

            self.master.create_rectangle(xmin, ymin, xmax, ymax, fill = fill, outline = outline)

class CellGrid(Canvas):
    def __init__(self,master, rowNumber, columnNumber, cellSize, init_grid=None, *args, **kwargs):
        Canvas.__init__(self, master, width = cellSize * columnNumber , height = cellSize * rowNumber, *args, **kwargs)

        self.cellSize = cellSize
        
        self.num_rows = rowNumber
        self.num_cols = columnNumber
        
        self.grid = []
        for row in range(rowNumber):

            line = []
            for column in range(columnNumber):
                line.append(Cell(self, column, row, cellSize) if init_grid==None else Cell(self, column, row, cellSize, init_grid[row][column].state))

            self.grid.append(line)

        #memorize the cells that have been modified to avoid many switching of state during mouse motion.
        self.switched = []

        #bind click action
        self.bind("<Button-1>", self.handleMouseClick)  
        #bind moving while clicking
        self.bind("<B1-Motion>", self.handleMouseMotion)
        #bind release button action - clear the memory of midified cells.
        self.bind("<ButtonRelease-1>", lambda event: self.switched.clear())

        self.draw()



    def draw(self):
        for row in self.grid:
            for cell in row:
                cell.draw()

    def _eventCoords(self, event):
        row = int(event.y / self.cellSize)
        column = int(event.x / self.cellSize)
        return row, column

    def handleMouseClick(self, event):
        row, column = self._eventCoords(event)
        cell = self.grid[row][column]
        cell._switch()
        cell.draw()
        #add the cell to the list of cell switched during the click
        self.switched.append(cell)

    def handleMouseMotion(self, event):
        row, column = self._eventCoords(event)
        cell = self.grid[row%self.num_rows][column%self.num_cols]

        if cell not in self.switched:
            cell._switch()
            cell.draw()
            self.switched.append(cell)



app = Tk()

#tkinter.Button(app.text ='').pack()
tkinter.Entry(app).pack()

Grid = CellGrid(app, 50, 50, 15)
Grid.pack()


app.mainloop()


## Toggle Pedestrian Motion
Upon clicking the Left Mouse Button, the user can now toggle pedestrian movement towards the target

In [4]:
class Simulation(Canvas):
    def __init__(self, root, rowNumber, columnNumber, cellSize, init_grid, pedestrian, target, distance_matrix, *args, **kwargs):
        Canvas.__init__(self, root, width = cellSize * columnNumber , height = cellSize * rowNumber, *args, **kwargs)
        
        self.grid = []
        self.row_size = rowNumber
        self.col_size = columnNumber
        self.pedestrian = pedestrian
        self.target = target
        #self.grid = init_grid
        self.distance_matrix = distance_matrix

        for row in range(rowNumber):
            line = []
            for column in range(columnNumber):
                line.append(Cell(self, column, row, cellSize) if init_grid==None else Cell(self, column, row, cellSize, init_grid[row][column].state))

            self.grid.append(line)
        
        self.draw()
        
        self.bind("<Button-1>", self.handleMouseClick)
        
                
    def draw(self):
        for row in self.grid:
            for cell in row:
                cell.draw(cell.state)
                
    def handleMouseClick(self, event):
        self.grid, self.pedestrian = update(self.grid, self.pedestrian, self.target, self.distance_matrix)
        self.draw()
    

##Accumulate Pedestrians and Target from the grid
pedestrians = []
targets = []
for row in range(len(Grid.grid)):
    for col in range(len(Grid.grid[0])):
        if Grid.grid[row][col].state=='pedestrian':
            pedestrians.append([col+1,row+1])
        elif Grid.grid[row][col].state=='target':
            targets.append([col+1,row+1])


# Calculate distance matrix
dist = Distance("euclidean")
distance_matrix = dist.get_distance(Grid.grid, targets)

print(distance_matrix)
target_grid_to_image(distance_matrix)
root = Tk()

application = Simulation(root, 50, 50, 20, Grid.grid, pedestrians, targets, distance_matrix)
application.pack()

root.mainloop()

    
    

[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]] [[12, 13], [40, 31]]
[[17.69180601 16.97056275 16.2788206  ... 36.05551275 37.
  37.94733192]
 [17.02938637 16.2788206  15.55634919 ... 35.73513677 36.68787266
  37.64306045]
 [16.40121947 15.62049935 14.86606875 ... 35.44009029 36.40054945
  37.36308338]
 ...
 [31.78049716 30.8058436  29.83286778 ... 17.4642492  18.38477631
  19.31320792]
 [32.01562119 31.04834939 30.08321791 ... 17.88854382 18.78829423
  19.6977156 ]
 [32.28002478 31.32091953 30.3644529  ... 18.35755975 19.23538406
  20.1246118 ]]
