In [2]:
import numpy as np
import heapq


In [3]:

class Node:
    def __init__(self, x, y):
        self.x = x
        self.y = y

        self.distance = 1e9
        self.visited = False
        self.blocked = False

    def __lt__(self, other):
        return self.distance < other.distance



# Horizontal and VerticalDistance
hVDistance = 1.0
# Diagonal Distance
dDistance = 1.4


class Dijkstra:
    

    def distance(self, matrix, si, sj):
        """
        Dijkstra for grid
        
        matrix: boolean matrix of size (n, n). 0 = Blocked, 1 = Not blocked
        si: x coordinate of target
        sj : y coordinate of target
        return: matrix of size (n, n) with distances from each grid location to target (si, sj)
        """
        
        size = len(matrix)
        gridArea = [[None for i in range(size)] for j in range(size)]

        # Creating nodes and finding blocked cells in matrix and mapping accordingly to our grid
        for i in range(size):
            for j in range(size):
                gridArea[i][j] = Node(i, j)
                if matrix[i][j] == False:
                    gridArea[i][j].blocked = True

        # setting start distance to 0.
        # All other nodes will have infinity distance at the beginning
        start = gridArea[si][sj]
        start.distance = 0

        queueB = []
        heapq.heappush(queueB, start)
  

        while len(queueB) > 0:
            current = heapq.heappop(queueB)

            # Top
            if current.x - 1 >= 0:
                
                # Top Top
                t = gridArea[current.x - 1][current.y]

                if not t.visited and not t.blocked and t.distance > current.distance + hVDistance:
                    t.distance = current.distance + hVDistance
                    heapq.heappush(queueB, t)

                # Top Left
                if current.y - 1 > 0:
                    t = gridArea[current.x - 1][current.y - 1]
                    if not t.visited and not t.blocked and t.distance > current.distance + dDistance:
                        t.distance = current.distance + dDistance
                        heapq.heappush(queueB, t)

                # Top Right
                if current.y + 1 < size:
                    t = gridArea[current.x - 1][current.y + 1]
                    if not t.visited and not t.blocked and t.distance > current.distance + dDistance:
                        t.distance = current.distance + dDistance
                        heapq.heappush(queueB, t)

            # Left
            if current.y - 1 > 0:
                t = gridArea[current.x][current.y - 1]
                if not t.visited and not t.blocked and t.distance > current.distance + hVDistance:
                    t.distance = current.distance + hVDistance
                    heapq.heappush(queueB, t)

            # Right
            if current.y + 1 < size:
                t = gridArea[current.x][current.y + 1]
                if not t.visited and not t.blocked and t.distance > current.distance + hVDistance:
                    t.distance = current.distance + hVDistance
                    heapq.heappush(queueB, t)

            # Down
            if current.x + 1 < size:

                # Down Down
                t = gridArea[current.x + 1][current.y]

                if not t.visited and not t.blocked and t.distance > current.distance + hVDistance:
                    t.distance = current.distance + hVDistance
                    heapq.heappush(queueB, t)

                # Down Left
                if current.y - 1 >= 0:
                    t = gridArea[current.x + 1][current.y - 1]
                    if not t.visited and not t.blocked and t.distance > current.distance + dDistance:
                        t.distance = current.distance + dDistance
                        heapq.heappush(queueB, t)

                # Down Right
                if current.y + 1 < size:
                    t = gridArea[current.x + 1][current.y + 1]
                    if not t.visited and not t.blocked and t.distance > current.distance + dDistance:
                        t.distance = current.distance + dDistance
                        heapq.heappush(queueB, t)

            current.visited = True
            
        distance_matrix = np.array([[i.distance for i in j] for j in gridArea])

        return distance_matrix




In [4]:
matrix = np.ones((20, 20))

# BLOCKED
matrix[4:6, 4:10] = 0
matrix[4:15, 8:10] = 0
matrix[13:15, 4:10] = 0

print(matrix.astype(int))

[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]


In [5]:
# TARGET

target = (10, 4)
si, sj = target
matrix[si, sj] = 3

print(matrix.astype(int))

[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 3 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]


In [6]:
dijkstra = Dijkstra()

distance_matrix = dijkstra.distance(matrix, si, sj)

print(distance_matrix)


[[1.36e+01 1.12e+01 1.08e+01 1.04e+01 1.08e+01 1.12e+01 1.16e+01 1.20e+01
  1.30e+01 1.40e+01 1.50e+01 1.60e+01 1.70e+01 1.80e+01 1.90e+01 2.00e+01
  2.10e+01 2.20e+01 2.30e+01 2.40e+01]
 [1.26e+01 1.02e+01 9.80e+00 9.40e+00 9.80e+00 1.02e+01 1.06e+01 1.16e+01
  1.26e+01 1.36e+01 1.46e+01 1.56e+01 1.66e+01 1.76e+01 1.86e+01 1.96e+01
  2.06e+01 2.16e+01 2.26e+01 2.36e+01]
 [1.16e+01 9.20e+00 8.80e+00 8.40e+00 8.80e+00 9.20e+00 1.02e+01 1.12e+01
  1.22e+01 1.32e+01 1.42e+01 1.52e+01 1.62e+01 1.72e+01 1.82e+01 1.92e+01
  2.02e+01 2.12e+01 2.22e+01 2.32e+01]
 [1.06e+01 8.20e+00 7.80e+00 7.40e+00 7.80e+00 8.80e+00 9.80e+00 1.08e+01
  1.18e+01 1.28e+01 1.38e+01 1.48e+01 1.58e+01 1.68e+01 1.78e+01 1.88e+01
  1.98e+01 2.08e+01 2.18e+01 2.28e+01]
 [9.60e+00 7.20e+00 6.80e+00 6.40e+00 1.00e+09 1.00e+09 1.00e+09 1.00e+09
  1.00e+09 1.00e+09 1.42e+01 1.52e+01 1.62e+01 1.72e+01 1.82e+01 1.92e+01
  2.02e+01 2.12e+01 2.22e+01 2.32e+01]
 [8.60e+00 6.20e+00 5.80e+00 5.40e+00 1.00e+09 1.00e+09 1.00e+09 

In [7]:
from PIL import Image

def target_grid_to_image(target_distance_grids, size):
    """
    Creates a colored image based on the distance to the target stored in
    self.target_distance_gids.
    :param canvas: the canvas that holds the image.
    :param old_image_id: the id of the old grid image.
    """
    im = Image.new(mode="RGB", size=(size, size))
    pix = im.load()
    for x in range(size):
        for y in range(size):
            target_distance = target_distance_grids[x][y]
            pix[y, x] = (max(0, min(255, int(10 * target_distance) - 0 * 255)),
                         max(0, min(255, int(10 * target_distance) - 1 * 255)),
                         max(0, min(255, int(10 * target_distance) - 2 * 255)))
            
    
    im = im.resize((1000, 1000), Image.NONE)
    im.show()
    

target_grid_to_image(distance_matrix, len(distance_matrix))